---
abstract: 'For managing collections of Bib::CrossRef references.'
author:
  - 'Doug Leith <dougleith@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bib-Tools
no_index:
  directory:
    - t
    - inc
requires:
  Bib::CrossRef: 0.07
  BibTeX::Parser: 0
  HTML::Entities: 0
  HTML::TreeBuilder::XPath: 0
  IO::File: 0
  JSON: 0
  LWP::UserAgent: 0
  Test::More: 0
  URI::Escape: 0
  XML::Simple: 0
version: 0.11
